### ISSUE TITLE
password length specified as minimum of 10 caharacters. This is wrong .see the table below

### ISSUE THREAD

**Issue by oariyo** [NETOPRD/EDM-Issues#10]
S/N	Password Security Settings	Good Practice	ELM	Remark
1	Minimum Password Length	6-8 Characters	8 characters	Adequate
2	Lockout Threshold	3 Invalid Log-on Attempts	5 Invalid Log-on Attempts	Inadequate
3	Alphanumeric Enabled	Yes	Yes	Adequate
4	Password History	10-12 Passwords	Not Defined	Inadequate
5	Maximum Password Life	30-90 Days	Not Defined	Inadequate
6	Session Time-out	5-15 Minutes	15 Minutes	Adequate
7	Password Change at first log on	 Yes	Yes	Adequate

**Comment by NETOPRD** [comment]
The password settings page is for you to modify everything there according to your own preferred standard. Please modify as you want.
However if there is any missing item on the form, kindly highlight
