### ISSUE TITLE
password setting showing error unauthorised link for system administrator

### ISSUE THREAD

**Issue by oariyo** [NETOPRD/EDM-Issues#11]
![image](https://cloud.githubusercontent.com/assets/24825583/21576499/60c30d6c-cf32-11e6-8e2c-86b0fb39b7f6.png)

**Comment by oyes** [comment]
Please sign out and sign in again. This is happening because the session has expired.

**Comment by oariyo** [comment]
still same

**Comment by NETOPRD** [comment]
Fixed, needs to be deployed
