### ISSUE TITLE
POST CREDIT NOTE & DEBIT NOTE

### ISSUE THREAD

**Issue by rhymestech** [NETOPRD/EDM-Issues#13]
When Distributor is selected at the point of posting credit note, it doesn't add the Distributor. Same thing is happening at the point of posting Debit Note. It automatically means Credit and Debit Note cannot be created.
![image](https://cloud.githubusercontent.com/assets/24911909/21637854/27bdc522-d269-11e6-8b15-d27fd73d5b85.png)

**Comment by madu23** [comment]
Will look into it and revert

**Comment by madu23** [comment]
Post Credit and Debit Note resolved
