### ISSUE TITLE
No network status report from desktop app 

### ISSUE THREAD

**Issue by lysed-ab** [NETOPRD/EDM-Issues#2]
When trying to login from the desktop app with the network disconnected, i dont get any error message. i expect to get an error like "UNABLE TO CONNECT TO SERVER" at least to know what is going on

**Comment by oyes** [comment]
There are two sides to the problem, when your local network is disconnected and when the server is down. We would have to handle these situations together, so we are thinking of displaying "Error connecting to the server. Kindly contact admin for help"

**Comment by lysed-ab** [comment]
Error connecting to server, Unable to communicate with server, Network connection failure. Any one of the above should be fine

**Comment by NETOPRD** [comment]
Fixed
