### ISSUE TITLE
oariyo@mdslogistics.net created  but could not login depot and client acccess attached

### ISSUE THREAD

**Issue by oariyo** [NETOPRD/EDM-Issues#7]
![image](https://cloud.githubusercontent.com/assets/24825583/21563407/6c092158-ce82-11e6-849d-ee9c4fd128d5.png)

**Comment by NETOPRD** [comment]
This issue has been reviewed, the problem arose as a result of adding a users to multiple user groups. Which is not allowed by the system.
This gives rise to another feature that needs to be implemented in code
